spring:
  application:
    name: favorite-place
  profiles:
    #DB 설정
    include: db

# mybatis 설정
mybatis:
  configuration:
    #카멜 케이스(camel case)와 스네이크 케이스(snake case)를 자동 매핑할지 여부를 설정합니다. 기본값은 false입니다.
    map-underscore-to-camel-case: true
    #모든 SQL 구문의 기본 타임아웃 값을 설정합니다. 기본값은 null입니다.
    default-statement-timeout: 20
  mapper-locations:
    - "mybatis/mapper/**/*.xml"