spring:
  application:
    name: favorite-place
  profiles:
    #DB 설정
    include: db

#JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true